sudo: true
language: haskell

git:
  depth: 3

cabal: "2.4"

cache:
  directories:
  - "$HOME/.cabal/store"

matrix:
  include:
  - ghc: 8.6.3

install:
  - ghc --version
  - cabal --version
  - cabal new-update
  - cabal new-build --enable-tests

script:
  - cabal new-test --enable-tests
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint .

notifications:
  email: false